Data: Cours.o EDT.o Enseignant.o Filiere.o Groupe.o Matiere.o Ressource.o Salle.o Universite.o

Cours.o: ../les_h/Cours.h Cours.cc 
	g++ -o Cours.o -c Cours.cc -Wall

Filiere.o: ../les_h/Filiere.h Filiere.cc
	g++ -o Filiere.o -c Filiere.cc -Wall

EDT.o: ../les_h/EDT.h EDT.cc
	g++ -o EDT.o -c EDT.cc -Wall

Enseignant.o: ../les_h/Enseignant.h Enseignant.cc
	g++ -o Enseignant.o -c Enseignant.cc -Wall
	
Groupe.o: ../les_h/Groupe.h Groupe.cc 
	g++ -o Groupe.o -c Groupe.cc -Wall
	
Matiere.o: ../les_h/Matiere.h Matiere.cc
	g++ -o Matiere.o -c Matiere.cc -Wall

Ressource.o: ../les_h/Ressource.h Ressource.cc
	g++ -o Ressource.o -c Ressource.cc -Wall
	
Salle.o: ../les_h/Salle.h Salle.cc
	g++ -o Salle.o -c Salle.cc -Wall
	
Universite.o: ../les_h/Universite.h Universite.cc
	g++ -o Universite.o -c Universite.cc -Wall

clean:
	rm -f *.o
