Data: Universite.o Ressource.o Salle.o Matiere.o Groupe.o Filiere.o Enseignant.o EDT.o Cours.o
 
Universite.o: Universite.cc Universite.h
	g++ -Wall -c Universite.cc
	
Salle.o: Salle.cc Salle.h
	g++ -Wall -c Salle.cc	
	
Ressource.o: Ressource.cc Ressource.h
	g++ -Wall -c Ressource.cc
	
Matiere.o: Matiere.cc Matiere.h
	g++ -Wall -c Matiere.cc
	
Groupe.o: Groupe.cc Groupe.h
	g++ -Wall -c Groupe.cc
	
Filiere.o: Filiere.cc Filiere.h
	g++ -Wall -c Filiere.cc
	
Enseignant.o: Enseignant.cc Enseignant.h
	g++ -Wall -c Enseignant.cc
	
EDT.o: EDT.cc EDT.h
	g++ -Wall -c EDT.cc
	
Cours.o: Cours.cc Cours.h
	g++ -Wall -c Cours.cc

clean: 
	rm -f *.h.gch
	rm -f *.o

