Data: Universite.o Ressource.o Salle.o Matiere.o Groupe.o Filiere.o Enseignant.o EDT.o Cours.o
 
Universite.o: Universite.cc
	g++ -Wall -c Universite.cc
	
Salle.o: Salle.cc 
	g++ -Wall -c Salle.cc	
	
Ressource.o: Ressource.cc 
	g++ -Wall -c Ressource.cc
	
Matiere.o: Matiere.cc 
	g++ -Wall -c Matiere.cc
	
Groupe.o: Groupe.cc
	g++ -Wall -c Groupe.cc
	
Filiere.o: Filiere.cc
	g++ -Wall -c Filiere.cc
	
Enseignant.o: Enseignant.cc
	g++ -Wall -c Enseignant.cc
	
EDT.o: EDT.cc
	g++ -Wall -c EDT.cc
	
Cours.o: Cours.cc
	g++ -Wall -c Cours.cc

clean: 
	rm -f *.h.gch
	rm -f *.o

